# Generated by Django 5.2 on 2025-05-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofilemodel',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
