# Generated by Django 5.2 on 2025-05-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileModel',
            new_name='SalePunchModel',
        ),
    ]
