# Generated by Django 5.2 on 2025-06-06 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('paid_trans_type', models.CharField(blank=True, choices=[('cash', 'cash'), ('bank', 'bank'), ('cheque', 'cheque')], default='cash', max_length=100, null=True)),
                ('pay_type', models.CharField(blank=True, choices=[('fixed amount', 'fixed amount'), ('minimum required amount', 'minimum required amount')], max_length=100, null=True)),
                ('next_pay_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_reason', models.TextField(blank=True, null=True)),
                ('pos_next_pend_pay', models.FloatField(blank=True, default=0.0, null=True)),
                ('res_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_date_and_time', models.DateTimeField()),
                ('emi_tobe_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('visit_type', models.CharField(blank=True, default='direct visit', max_length=100, null=True)),
                ('visit_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('others_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.othermodel')),
                ('paid_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.paidmodel')),
                ('unpaid_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.unpaidmodel')),
            ],
        ),
    ]
