# Generated by Django 5.2 on 2025-06-17 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastVisitDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls_visit_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ls_visit_date', models.DateField(blank=True, null=True)),
                ('ls_visit_status', models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('other', 'other')], default='unpaid', null=True)),
                ('ls_unit_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('ls_agent_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ls_agent_data', to=settings.AUTH_USER_MODEL)),
                ('ls_customer_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ls_customer_prof_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.customerprofilemodel')),
                ('ls_salepunch_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.salepunchmodel')),
            ],
        ),
    ]
