# Generated by Django 5.2 on 2025-05-22 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='reciept_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please Provide a 10 digit number', regex='^\\d{10}')]),
        ),
    ]
