# Generated by Django 5.2 on 2025-05-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0002_rename_userprofilemodel_salepunchmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_model',
        ),
    ]
