# Generated by Django 5.2 on 2025-06-06 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0002_othermodel_paidmodel_unpaidmodel_collectionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='created_at',
            new_name='cm_created_at',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='emi_tobe_paid',
            new_name='cm_emi_tobe_paid',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='full_name',
            new_name='cm_full_name',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='next_date_and_time',
            new_name='cm_next_date_and_time',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='others_data',
            new_name='cm_others_data',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='paid_data',
            new_name='cm_paid_data',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='unpaid_data',
            new_name='cm_unpaid_data',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='visit_count',
            new_name='cm_visit_count',
        ),
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='visit_type',
            new_name='cm_visit_type',
        ),
        migrations.RenameField(
            model_name='othermodel',
            old_name='created_at',
            new_name='other_created_at',
        ),
        migrations.RenameField(
            model_name='othermodel',
            old_name='remarks',
            new_name='other_remarks',
        ),
        migrations.RenameField(
            model_name='paidmodel',
            old_name='created_at',
            new_name='paid_created_at',
        ),
        migrations.RenameField(
            model_name='paidmodel',
            old_name='next_pay_date',
            new_name='paid_next_pay_date',
        ),
        migrations.RenameField(
            model_name='paidmodel',
            old_name='pay_type',
            new_name='paid_pay_type',
        ),
        migrations.RenameField(
            model_name='unpaidmodel',
            old_name='created_at',
            new_name='unpaid_created_at',
        ),
        migrations.RenameField(
            model_name='unpaidmodel',
            old_name='pos_next_pend_pay',
            new_name='unpaid_pos_next_pend_pay',
        ),
        migrations.RenameField(
            model_name='unpaidmodel',
            old_name='res_date',
            new_name='unpaid_res_date',
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='cm_agent_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_agent_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='cm_customer_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='cm_customer_prof_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.customerprofilemodel'),
        ),
        migrations.AddField(
            model_name='othermodel',
            name='other_agent_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_agent_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othermodel',
            name='other_customer_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othermodel',
            name='other_customer_prof_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.customerprofilemodel'),
        ),
        migrations.AddField(
            model_name='paidmodel',
            name='paid_agent_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_agent_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paidmodel',
            name='paid_customer_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paidmodel',
            name='paid_customer_prof_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.customerprofilemodel'),
        ),
        migrations.AddField(
            model_name='unpaidmodel',
            name='unpaid_agent_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_agent_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidmodel',
            name='unpaid_customer_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidmodel',
            name='unpaid_customer_prof_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.customerprofilemodel'),
        ),
    ]
