# Generated by Django 5.2 on 2025-06-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0002_lastvisitdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='cm_last_visited_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.lastvisitdetailsmodel'),
        ),
    ]
