# Generated by Django 5.2 on 2025-05-22 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0002_alter_customerprofilemodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='whatsapp_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit valid number', regex='\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
