# Generated by Django 5.2 on 2025-06-11 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0002_alter_collectionmodel_cm_kyc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_kyc',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='KYC number should be 12 digit', regex='^\\d{12}')]),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_uid',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='UID number should be 12 digit', regex='^\\d{12}')]),
        ),
    ]
