# Generated by Django 5.2 on 2025-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0003_rename_created_at_collectionmodel_cm_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaidmodel',
            name='unpaid_pos_next_pend_pay',
            field=models.CharField(blank=True, choices=[('salary/income', 'salary/income'), ('anticipating money', 'anticipating money'), ('borrowed', 'borrowed'), ('money rolling', 'money rolling'), ('better financial profile', 'better financial profile')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unpaidmodel',
            name='unpaid_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
