# Generated by Django 5.2 on 2025-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0003_alter_collectionmodel_cm_kyc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='cm_reminder_data',
            new_name='cm_reminder_date',
        ),
        migrations.RemoveField(
            model_name='collectionmodel',
            name='cm_batch_choices',
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='cm_batch',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=10, null=True),
        ),
    ]
