# Generated by Django 5.2 on 2025-06-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0003_collectionmodel_cm_last_visited_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastvisitdetailsmodel',
            old_name='ls_customer_prof_date',
            new_name='ls_customer_prof_data',
        ),
    ]
