# Generated by Django 5.2 on 2025-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0004_alter_unpaidmodel_unpaid_pos_next_pend_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_next_date_and_time',
            field=models.DateField(),
        ),
    ]
