# Generated by Django 5.2 on 2025-06-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0004_rename_cm_reminder_data_collectionmodel_cm_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='cm_emi_sum',
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_collection_mode',
            field=models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_emi_tobe_paid',
            field=models.FloatField(blank=True, choices=[('by call', 'by call'), ('by visit', 'by visit')], default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_payment_mode',
            field=models.CharField(blank=True, choices=[('gpay', 'gpay'), ('direct', 'direct')], default='gpay', null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_visit_type',
            field=models.CharField(blank=True, choices=[('direct visit', 'direct visit'), ('phone', 'phone')], default='direct visit', max_length=100, null=True),
        ),
    ]
