# Generated by Django 5.2 on 2025-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0004_rename_ls_customer_prof_date_lastvisitdetailsmodel_ls_customer_prof_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='cm_payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('other', 'other')], default='unpaid', max_length=50, null=True),
        ),
    ]
