# Generated by Django 5.2 on 2025-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0005_collectionmodel_cm_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaidmodel',
            name='unpaid_reason',
            field=models.CharField(blank=True, choices=[('income date & collection date variation', 'income date & collection date variation'), ('rescentment of not getting kuri', 'rescentment of not getting kuri'), ('unexpected expenses', 'unexpected expenses'), ('payment unscheduled', 'payment unscheduled'), ('current over liability', 'current over liability'), ('unstructured financial behaviour', 'unstructured financial behaviour')], max_length=255, null=True),
        ),
    ]
