# Generated by Django 5.2 on 2025-05-26 12:21

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0005_alter_customerprofilemodel_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', blank=True, length=22, max_length=4, null=True, prefix='', unique=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
