# Generated by Django 5.2 on 2025-05-26 13:02

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0006_agentprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofilemodel',
            name='agent_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', blank=True, length=4, max_length=6, null=True, prefix='', unique=True),
        ),
    ]
