# Generated by Django 5.2 on 2025-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0006_alter_unpaidmodel_unpaid_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='cm_group',
            field=models.CharField(blank=True, choices=[('301', '301'), ('801', '801'), ('201', '201'), ('202', '202'), ('901', '901'), ('902', '902'), ('903', '903'), ('904', '904'), ('951', '951'), ('952', '952'), ('502', '502')], default='301', max_length=50, null=True),
        ),
    ]
