# Generated by Django 5.2 on 2025-05-27 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0007_alter_agentprofilemodel_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.agentprofilemodel'),
        ),
    ]
