# Generated by Django 5.2 on 2025-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0007_alter_collectionmodel_cm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermodel',
            name='other_created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidmodel',
            name='paid_created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidmodel',
            name='paid_next_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unpaidmodel',
            name='unpaid_created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unpaidmodel',
            name='unpaid_res_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
