# Generated by Django 5.2 on 2025-05-27 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0008_alter_customerprofilemodel_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a 10 digit number', regex='^\\d{10}')])),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
