# Generated by Django 5.2 on 2025-05-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0009_otprecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepunchmodel',
            name='signature_field',
            field=models.ImageField(blank=True, null=True, upload_to='\\signature'),
        ),
        migrations.AddField(
            model_name='salepunchmodel',
            name='video_field',
            field=models.FileField(blank=True, null=True, upload_to='\x0bideo'),
        ),
    ]
