# Generated by Django 5.2 on 2025-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0010_salepunchmodel_signature_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='signature_field',
            field=models.FileField(blank=True, null=True, upload_to='\\signature'),
        ),
    ]
