# Generated by Django 5.2 on 2025-05-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0011_alter_salepunchmodel_signature_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salepunchmodel',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='whatsapp',
        ),
    ]
