# Generated by Django 5.2 on 2025-05-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0013_salepunchmodel_customer_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepunchmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
