# Generated by Django 5.2 on 2025-05-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0014_salepunchmodel_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salepunchmodel',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
