# Generated by Django 5.2 on 2025-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0015_rename_customer_salepunchmodel_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='signature_field',
            field=models.FileField(blank=True, null=True, upload_to='signature/'),
        ),
        migrations.AlterField(
            model_name='salepunchmodel',
            name='video_field',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
