# Generated by Django 5.2 on 2025-05-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0016_alter_salepunchmodel_signature_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salepunchmodel',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
