# Generated by Django 5.2 on 2025-05-29 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0017_rename_customer_id_salepunchmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='emi_amount',
        ),
        migrations.CreateModel(
            name='LiabilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('emi_amount', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.customerprofilemodel')),
            ],
        ),
    ]
