# Generated by Django 5.2 on 2025-05-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0018_remove_salepunchmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepunchmodel',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
