# Generated by Django 5.2 on 2025-05-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0019_salepunchmodel_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilitiesmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='liabilitiesmodel',
            name='customer_prof',
        ),
        migrations.AddField(
            model_name='liabilitiesmodel',
            name='salepunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inkludechit.salepunchmodel'),
        ),
    ]
