# Generated by Django 5.2 on 2025-05-31 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0020_remove_liabilitiesmodel_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='kyc',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='KYC number should be 12 digit', regex='^\\d{12}')]),
        ),
        migrations.AlterField(
            model_name='salepunchmodel',
            name='uid',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='UID should be 12 digit', regex='^\\d{12}')]),
        ),
    ]
