# Generated by Django 5.2 on 2025-05-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0022_alter_salepunchmodel_kyc_alter_salepunchmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofilemodel',
            name='is_salepunch_created',
            field=models.BooleanField(default=False),
        ),
    ]
