# Generated by Django 5.2 on 2025-06-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0023_customerprofilemodel_is_salepunch_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='document_type',
            field=models.CharField(blank=True, choices=[('collateral', 'collateral'), ('non collateral', 'non collateral')], default='collateral', max_length=100, null=True),
        ),
    ]
