# Generated by Django 5.2 on 2025-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0024_alter_productmodel_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofilemodel',
            name='is_salepunch_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
