# Generated by Django 5.2 on 2025-06-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0025_alter_customerprofilemodel_is_salepunch_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofilemodel',
            name='is_salepunch_created',
        ),
    ]
