# Generated by Django 5.2 on 2025-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0029_remove_customerprofilemodel_is_salepunch_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofilemodel',
            name='is_salepunch_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
